// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvza6AwVbokf9oZgbiIXzqnPK2TApNpKE',
    appId: '1:1050381680231:web:a3ab5cb8781e2d4f89dec2',
    messagingSenderId: '1050381680231',
    projectId: 'farmhousebooking-ce783',
    authDomain: 'farmhousebooking-ce783.firebaseapp.com',
    storageBucket: 'farmhousebooking-ce783.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARX6xz6GcLcrayJKJeSiH55nvrJxBZUkE',
    appId: '1:1050381680231:android:b225d500f491524089dec2',
    messagingSenderId: '1050381680231',
    projectId: 'farmhousebooking-ce783',
    storageBucket: 'farmhousebooking-ce783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkkX--_XZDi1BV_SSEKomGO1UauoSulRU',
    appId: '1:1050381680231:ios:04c641e040b461b189dec2',
    messagingSenderId: '1050381680231',
    projectId: 'farmhousebooking-ce783',
    storageBucket: 'farmhousebooking-ce783.appspot.com',
    iosClientId: '1050381680231-t0rok4g2qbf9o9ed8kit89lcuiu1jkpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.resortbooking',
  );
}
